### ISSUE TITLE
parse_trans dependency

### ISSUE THREAD

**Issue by take-five** [uwiger/jobs#24]
Hello,

I have a project with `jobs` and `hackney` as a dependencies, but I can't update `hackney` to latest version and apply security fixes without manually overriding `parse_trans` dependency to `3.2.0`, because latest `hackney` depends on `certifi 2.3.1`, which depends on `parse_trans 3.2.0`, but `jobs` depends on `parse_trans 3.0.0`.

Is there anything that prevents `jobs` to be dependent on latest `parse_trans` (or maybe on `parse_trans 3.x`)?

**Comment by tolbrino** [comment]
Using `3.3.0` now.
