### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [uwiger/jobs#36]
Would it be possible to tag a release, here and in Hex.pm?

Many thanks.

If possible:

- [ ] wait until `parse_trans` is deemed OTP-24 ready and updated as a dep. in `jobs`
- [x] ~^ also means waiting for https://github.com/uwiger/parse_trans/pull/45 to be accepted (or an otherwise different solution that provides the same correction)~

**Comment by paulo-ferraz-oliveira** [comment]
@uwiger, this would mean a `parse_trans` release and subsequent update here. Is this desired?

**Comment by paulo-ferraz-oliveira** [comment]
https://hex.pm/packages/parse_trans/3.4.0's been release, so this can now happen.

**Comment by uwiger** [comment]
Version 0.10.0 now pushed to hex.pm

**Comment by paulo-ferraz-oliveira** [comment]
Cool. Thanks.
